export const SEOULCITY = [
    '서울시 종로구',
    '서울시 중구',
    '서울시 용산구',
    '서울시 성동구',
    '서울시 광진구',
    '서울시 동대문구',
    '서울시 중랑구',
    '서울시 성북구',
    '서울시 강북구',
    '서울시 도봉구',
    '서울시 노원구',
    '서울시 은평구',
    '서울시 서대문구',
    '서울시 마포구',
    '서울시 양천구',
    '서울시 강서구',
    '서울시 구로구',
    '서울시 금천구',
    '서울시 영등포구',
    '서울시 동작구',
    '서울시 관악구',
    '서울시 서초구',
    '서울시 강남구',
    '서울시 송파구',
    '서울시 강동구',
];

export const AVAILABLEDAYS = [
    { label: '월 오전', value: 'Monday am' },
    { label: '화 오전', value: 'Tuesday am' },
    { label: '수 오전', value: 'Wednesday am' },
    { label: '목 오전', value: 'Thursday am' },
    { label: '금 오전', value: 'Friday am' },
    { label: '토 오전', value: 'Saturday am' },
    { label: '일 오전', value: 'Sunday am' },
    { label: '월 오후', value: 'Monday pm' },
    { label: '화 오후', value: 'Tuesday pm' },
    { label: '수 오후', value: 'Wednesday pm' },
    { label: '목 오후', value: 'Thursday pm' },
    { label: '금 오후', value: 'Friday pm' },
    { label: '토 오후', value: 'Saturday pm' },
    { label: '일 오후', value: 'Sunday pm' },
];
